### ISSUE TITLE
Prevent usage of functions marked as private outside of their module

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#467]
Currently, marking a function as `private` is purely informative. Ideally, the compiler should enforce that the function isn’t used outside that module. It should also cover interesting cases like:

```clojure
(defmodule T
  (private f)
  (defn f [] (println* "I can’t be called outside!"))
)
(T.f) ; this should fail
(defmodule T
  (defn f2 [] (f)) ; this should work, since it’s inside the module, though in a different form
)
```

Cheers

**Comment by scolsen** [comment]
After #893 we sort of have this behavior. 

```clojure
(defmodule T
  (private f)
  (defn f [] (println* "I can’t be called outside!))
  (defn ff [] (f)) ;; works
)

(T.f) ;; privacy error
```

But the double-module declaration case actually won't work:

```
(defmodule T
  (private f)
  (defn f [] (println* "I can’t be called outside!))
  (defn ff [] (f)) ;; works
)

(defmodule T
  (defn fff [] (f)) ;; also throws a privacy error!
)
```

However I'm not sure why that's happening--the type to module case works as expected:

```clojure
(deftype Foo [bar Int])

(private Foo.bar)

(defmodule Foo
  (defn get [foo]
    (Foo.bar foo))
)
```

But we're almost there!

**Comment by scolsen** [comment]
Hm, I definitely need to fix something in the privacy checking impl--it's not catching all the cases I'd expect!

**Comment by eriksvedang** [comment]
Perhaps this was fixed with a recent PR?

**Comment by hellerve** [comment]
Actually, it seems as if there are no privacy errors anymore.

**Comment by scolsen** [comment]
Hm, that's odd--one thing I did notice yesterday is that we only check privacy in `Expand.hs`--we probably need several checks in `Eval.hs` as well. Not really sure how I missed that the first time around, but ce la vie

**Comment by scolsen** [comment]
@hellerve do you have an example of cases that don't work? I still see a privacy error when I run the following:

```clojure
鲤 (defmodule T (private f) (defn f [] "foo"))
鲤 (T.f)
The binding: T.f is private; it may only be used within the module that defines it. at REPL:1:2.
```

**Comment by hellerve** [comment]
Mhm, it actually seems to work for me now, so maybe I did something wrong!

**Comment by scolsen** [comment]
looks like it doesn't work for dynamics, though

**Comment by scolsen** [comment]
It has something to do w/ the way we handle contexts for Dynamics, which is different than the way we handle them for statics, but I'm having a hard time figuring it out

**Comment by scolsen** [comment]
I'm fairly stumped on how to do this correctly. I'm not entirely sure what to set in the `Context` to ensure dynamics are aware of their context when resolving their bodies.

Right now the problem seems to stem from the way we evaluate dynamic function bodies in `apply` in `Eval.hs` -- the context of the function isn't kept around, so even though we should know that the body of:

`(defmodule T ... (defn ff [] (T.f))`

is ok when `(T.ff)` by the time we eval `T.f` we don't know that it's called in the context of `T.ff`'s body, thus it fails a privacy check even though it's technically allowed.

**Comment by hellerve** [comment]
I like this discussion, and I empathize with your stumpedness. The following comment has nothing to do with that (sorry).

One note that I can think about here that is interesting will be about macros in modules: are they allowed to call private functions? Technically they shouldn’t, if we take them as transformations that happen "in place": the context should be that of the caller, not that of the macro. But it might make sense for them to be able to do this? I’m not quite sure what to do.

**Comment by eriksvedang** [comment]
Perhaps dynamic code just should be allowed to access any code? Kind of goes in line with not having types checked :) And when we get to the static pass those will still be checked so you can still prevent a lot of user errors with this feature.

**Comment by hellerve** [comment]
I think the current behaviour is probably fine?

**Comment by scolsen** [comment]
Another question, given: 

```
(defmodule T
  (defmodule F
     (private q)
   )
   (defn foo [] (q))
)
```

Should this throw a privacy error? Or should parents env's have access to their children's private bindings?

**Comment by eriksvedang** [comment]
@scolsen To me, the most logical is that it is a privacy error since it mirrors how the global env works in regards to its child envs (if T was the global env, accessing F.q would be an error). What do you think?

**Comment by scolsen** [comment]
Sounds good to me!
